# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1369, 752)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 30, 1361, 651))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.yatab = QtWidgets.QWidget()
        self.yatab.setObjectName("yatab")
        self.tabWidget2 = QtWidgets.QTabWidget(self.yatab)
        self.tabWidget2.setGeometry(QtCore.QRect(0, 0, 261, 611))
        self.tabWidget2.setObjectName("tabWidget2")
        self.kstab = QtWidgets.QWidget()
        self.kstab.setObjectName("kstab")
        self.kstree = QtWidgets.QTreeWidget(self.kstab)
        self.kstree.setGeometry(QtCore.QRect(0, 0, 251, 571))
        self.kstree.setRootIsDecorated(True)
        self.kstree.setObjectName("kstree")
        self.kstree.headerItem().setText(0, "1")
        self.tabWidget2.addTab(self.kstab, "")
        self.bwtab = QtWidgets.QWidget()
        self.bwtab.setObjectName("bwtab")
        self.bwtree = QtWidgets.QTreeWidget(self.bwtab)
        self.bwtree.setGeometry(QtCore.QRect(0, 0, 251, 551))
        self.bwtree.setObjectName("bwtree")
        self.bwtree.headerItem().setText(0, "1")
        self.tabWidget2.addTab(self.bwtab, "")
        self.groupBox = QtWidgets.QGroupBox(self.yatab)
        self.groupBox.setGeometry(QtCore.QRect(280, 30, 1071, 581))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 61, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(560, 30, 41, 31))
        self.label_3.setObjectName("label_3")
        self.ks_name = QtWidgets.QLineEdit(self.groupBox)
        self.ks_name.setGeometry(QtCore.QRect(610, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.ks_name.setFont(font)
        self.ks_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ks_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ks_name.setObjectName("ks_name")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 90, 54, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(560, 90, 54, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(30, 280, 41, 31))
        self.label_6.setObjectName("label_6")
        self.sick_des = QtWidgets.QTextBrowser(self.groupBox)
        self.sick_des.setGeometry(QtCore.QRect(100, 80, 451, 181))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.sick_des.setFont(font)
        self.sick_des.setObjectName("sick_des")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(560, 280, 54, 31))
        self.label_7.setObjectName("label_7")
        self.sick_res = QtWidgets.QTextBrowser(self.groupBox)
        self.sick_res.setGeometry(QtCore.QRect(610, 80, 461, 181))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.sick_res.setFont(font)
        self.sick_res.setObjectName("sick_res")
        self.sick_sym = QtWidgets.QTextBrowser(self.groupBox)
        self.sick_sym.setGeometry(QtCore.QRect(100, 270, 451, 291))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.sick_sym.setFont(font)
        self.sick_sym.setObjectName("sick_sym")
        self.sick_tre = QtWidgets.QTextBrowser(self.groupBox)
        self.sick_tre.setGeometry(QtCore.QRect(610, 270, 461, 291))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.sick_tre.setFont(font)
        self.sick_tre.setObjectName("sick_tre")
        self.sick_name = QtWidgets.QLineEdit(self.groupBox)
        self.sick_name.setGeometry(QtCore.QRect(100, 29, 71, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.sick_name.setFont(font)
        self.sick_name.setObjectName("sick_name")
        self.searchButton = QtWidgets.QPushButton(self.yatab)
        self.searchButton.setGeometry(QtCore.QRect(1260, 2, 75, 31))
        self.searchButton.setObjectName("searchButton")
        self.searchLine = QtWidgets.QLineEdit(self.yatab)
        self.searchLine.setGeometry(QtCore.QRect(1120, 0, 113, 31))
        self.searchLine.setObjectName("searchLine")
        self.tabWidget.addTab(self.yatab, "")
        self.fxtab = QtWidgets.QWidget()
        self.fxtab.setObjectName("fxtab")
        self.label_8 = QtWidgets.QLabel(self.fxtab)
        self.label_8.setGeometry(QtCore.QRect(920, 20, 181, 31))
        self.label_8.setObjectName("label_8")
        self.numLine = QtWidgets.QLineEdit(self.fxtab)
        self.numLine.setGeometry(QtCore.QRect(1110, 20, 61, 31))
        self.numLine.setObjectName("numLine")
        self.label_9 = QtWidgets.QLabel(self.fxtab)
        self.label_9.setGeometry(QtCore.QRect(1190, 20, 31, 31))
        self.label_9.setObjectName("label_9")
        self.widget = QtWidgets.QWidget(self.fxtab)
        self.widget.setGeometry(QtCore.QRect(120, 70, 1161, 541))
        self.widget.setObjectName("widget")
        self.huizhiButton = QtWidgets.QPushButton(self.fxtab)
        self.huizhiButton.setGeometry(QtCore.QRect(1230, 20, 75, 31))
        self.huizhiButton.setObjectName("huizhiButton")
        self.tabWidget.addTab(self.fxtab, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1020, 10, 141, 31))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Number = QtWidgets.QLCDNumber(self.centralwidget)
        self.Number.setGeometry(QtCore.QRect(1190, 10, 111, 31))
        self.Number.setObjectName("Number")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1369, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.kstab), _translate("MainWindow", "科室"))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.bwtab), _translate("MainWindow", "部位"))
        self.groupBox.setTitle(_translate("MainWindow", "详情"))
        self.label_2.setText(_translate("MainWindow", "疾病名"))
        self.label_3.setText(_translate("MainWindow", "科室"))
        self.label_4.setText(_translate("MainWindow", "简介"))
        self.label_5.setText(_translate("MainWindow", "病因"))
        self.label_6.setText(_translate("MainWindow", "症状"))
        self.sick_des.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt;\"><br /></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "治疗"))
        self.searchButton.setText(_translate("MainWindow", "搜索"))
        self.searchLine.setPlaceholderText(_translate("MainWindow", "搜索"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.yatab), _translate("MainWindow", "医案信息"))
        self.label_8.setText(_translate("MainWindow", "最容易发病的部位前"))
        self.numLine.setPlaceholderText(_translate("MainWindow", "6"))
        self.label_9.setText(_translate("MainWindow", "名"))
        self.huizhiButton.setText(_translate("MainWindow", "绘制"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fxtab), _translate("MainWindow", "数据分析"))
        self.label.setText(_translate("MainWindow", "共收录疾病"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

